/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import backend.Aluno;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Milena
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private List<Aluno> alunos = new ArrayList<>();
    private Aluno alunoAtual = null;
    private int proximaMatricula = 1;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        cbAlunos.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAlunos = new javax.swing.JComboBox<>();
        lblSistema = new javax.swing.JLabel();
        lblNomeAluno = new javax.swing.JLabel();
        lblCadastrarNovoAluno = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        lblCPFcadastrar = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblAlunosSelecionados = new javax.swing.JLabel();
        lblAlunos = new javax.swing.JLabel();
        lblMatriculas = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblCadastro = new javax.swing.JLabel();
        txtCadastro = new javax.swing.JTextField();
        btnVerDiciplinas = new javax.swing.JButton();
        lblAdicionarDisciplina = new javax.swing.JLabel();
        lblDisciplinas = new javax.swing.JLabel();
        txtDisciplinas = new javax.swing.JTextField();
        lblNotaFinal = new javax.swing.JLabel();
        txtNotaFinal = new javax.swing.JTextField();
        btnAdicionarDisciplinas = new javax.swing.JButton();

        cbAlunos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno  1", "Aluno  2", "Aluno  3", "Aluno  4" }));
        cbAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlunosActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSistema.setText("Sistema de Cadastro de Alunos");

        lblNomeAluno.setText("Nome Aluno:");

        lblCadastrarNovoAluno.setText("Cadastrar novo aluno:");

        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });

        lblCPFcadastrar.setText("CPF:");

        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar Aluno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblAlunosSelecionados.setText("Aluno Selecionado:");

        lblAlunos.setText("Alunos:");

        lblMatriculas.setText("Matricula:");

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        lblCPF.setText("CPF:");

        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        lblCadastro.setText("Cadastro:");

        txtCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastroActionPerformed(evt);
            }
        });

        btnVerDiciplinas.setText("Ver Disciplinas");
        btnVerDiciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDiciplinasActionPerformed(evt);
            }
        });

        lblAdicionarDisciplina.setText("Adicionar Disciplina:");

        lblDisciplinas.setText("Disciplinas:");

        txtDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisciplinasActionPerformed(evt);
            }
        });

        lblNotaFinal.setText("Nota Final:");

        txtNotaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaFinalActionPerformed(evt);
            }
        });

        btnAdicionarDisciplinas.setText("Adiconar Disciplina");
        btnAdicionarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarDisciplinasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(lblSistema))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeAluno)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCadastrarNovoAluno)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCPF))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMatriculas)
                                    .addComponent(lblAlunos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMatricula))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCPFcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdicionarDisciplinas)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnVerDiciplinas)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAdicionarDisciplina))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblNotaFinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNotaFinal))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblDisciplinas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblAlunosSelecionados))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSistema)
                .addGap(18, 18, 18)
                .addComponent(lblCadastrarNovoAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAluno)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPFcadastrar))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(9, 9, 9)
                .addComponent(lblAlunosSelecionados)
                .addGap(30, 30, 30)
                .addComponent(lblAlunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatriculas)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadastro)
                    .addComponent(txtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerDiciplinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdicionarDisciplina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisciplinas)
                    .addComponent(txtDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotaFinal)
                    .addComponent(txtNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionarDisciplinas)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = txtNomeAluno.getText().trim();
        String cpf = btnCadastrar.getText().trim();

        if (nome.isEmpty() || cpf.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha o nome e o CPF do aluno.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Aluno novoAluno = new Aluno(proximaMatricula++, nome, cpf);
        alunos.add(novoAluno);
        cbAlunos.addItem(nome);
        cbAlunos.setSelectedItem(nome);

        txtNomeAluno.setText("");
        btnCadastrar.setText("");

        javax.swing.JOptionPane.showMessageDialog(this, "Aluno '" + nome + "' cadastrado com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlunosActionPerformed
        int idx = cbAlunos.getSelectedIndex();
        if (idx < 0 || idx >= alunos.size()) return;

        alunoAtual = alunos.get(idx);
        txtMatricula.setText(String.valueOf(alunoAtual.getMatricula()));
        txtCPF.setText(alunoAtual.getCPF());
        txtCadastro.setText(String.format("%.2f", alunoAtual.getCR()));
    }//GEN-LAST:event_cbAlunosActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastroActionPerformed
    }//GEN-LAST:event_txtCadastroActionPerformed

    private void btnVerDiciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDiciplinasActionPerformed
        if (alunoAtual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um aluno primeiro.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        String disciplinas = alunoAtual.getDisciplinasMatriculadas();
        if (disciplinas.isEmpty()) {
            disciplinas = "Não existem disciplinas matriculadas";
        }
        javax.swing.JOptionPane.showMessageDialog(this,
            disciplinas + "\nCR: " + String.format("%.2f", alunoAtual.getCR()),
            "Disciplinas de " + alunoAtual.getNome(),
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerDiciplinasActionPerformed

    private void txtDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisciplinasActionPerformed
    }//GEN-LAST:event_txtDisciplinasActionPerformed

    private void btnAdicionarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarDisciplinasActionPerformed
        if (alunoAtual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um aluno primeiro.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nomeDisciplina = txtDisciplinas.getText().trim();
        String notaStr = txtNotaFinal.getText().trim();

        if (nomeDisciplina.isEmpty() || notaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha o nome da disciplina e a nota final.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        float nota;
        try {
            nota = Float.parseFloat(notaStr.replace(',', '.'));
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nota inválida. Use números (ex: 75.5).", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean sucesso = alunoAtual.setMatricularDisciplina(nomeDisciplina, nota);
        if (sucesso) {
            txtCadastro.setText(String.format("%.2f", alunoAtual.getCR()));
            txtDisciplinas.setText("");
            txtNotaFinal.setText("");
            javax.swing.JOptionPane.showMessageDialog(this, "Disciplina '" + nomeDisciplina + "' adicionada!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Disciplina '" + nomeDisciplina + "' já está cadastrada.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionarDisciplinasActionPerformed

    private void txtNotaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaFinalActionPerformed
    }//GEN-LAST:event_txtNotaFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarDisciplinas;
    private javax.swing.JTextField btnCadastrar;
    private javax.swing.JButton btnVerDiciplinas;
    private javax.swing.JComboBox<String> cbAlunos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAdicionarDisciplina;
    private javax.swing.JLabel lblAlunos;
    private javax.swing.JLabel lblAlunosSelecionados;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPFcadastrar;
    private javax.swing.JLabel lblCadastrarNovoAluno;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblDisciplinas;
    private javax.swing.JLabel lblMatriculas;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JLabel lblNotaFinal;
    private javax.swing.JLabel lblSistema;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCadastro;
    private javax.swing.JTextField txtDisciplinas;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNotaFinal;
    // End of variables declaration//GEN-END:variables
}
